# Generated by Django 6.0.5 on 2026-05-25 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_municipio_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('praia', 'Praia'), ('museu', 'Museu'), ('parque', 'Parque'), ('igreja', 'Igreja'), ('monumento', 'Monumento'), ('rio', 'Rio'), ('outro', 'Outro')], max_length=20)),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=150, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.bairro')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.municipio')),
            ],
        ),
    ]
