# Generated by Django 6.0.5 on 2026-05-27 23:47

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0005_alter_municipio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='bairro',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='municipio', chained_model_field='municipio', on_delete=django.db.models.deletion.DO_NOTHING, to='core.bairro'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='estado', chained_model_field='estado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.municipio'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.pontoturistico')),
            ],
        ),
    ]
