# Generated by Django 6.0.5 on 2026-05-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_pontoturistico_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
