# Generated by Django 6.0.5 on 2026-05-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='regiao',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
