# Generated by Django 6.0.5 on 2026-05-18 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estado_regiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='regiao',
            field=models.CharField(blank=True, choices=[('N', 'Norte'), ('NE', 'Nordeste'), ('CO', 'Centro-oeste'), ('SE', 'Sudeste'), ('S', 'Sul')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('populacao', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estado')),
            ],
        ),
    ]
