# Generated by Django 6.0.5 on 2026-05-18 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_estado_regiao_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('populacao', models.IntegerField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.municipio')),
            ],
        ),
    ]
