# Generated by Django 6.0.5 on 2026-05-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bairro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['nome', 'populacao'], 'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
    ]
